# cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: unite-cluster
  region: ap-south-1  # Adjust region as needed
  version: "1.28"    # Latest stable version

# Managed Node Group
managedNodeGroups:
  - name: unite-ng
    instanceType: t3.medium    # Better performance than t2.medium at same price
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    volumeSize: 20            # EBS volume size in GB
    privateNetworking: true   # Nodes in private subnets
    iam:
      withAddonPolicies:
        albIngress: true      # Required for ALB Ingress Controller
    tags:
      Environment: production
    
# VPC Configuration    
vpc:
  cidr: "10.0.0.0/16"
  nat:
    gateway: Single          # Single NAT Gateway to reduce costs

# Control Plane Logging - Minimal for cost saving
cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "api"]  # Only essential logs