apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod

---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: unite-cluster
  region: ap-south-1  
  version: "1.28"    

# Managed Node Group
managedNodeGroups:
  - name: unite-ng
    instanceType: t3.medium    
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    volumeSize: 20            
    privateNetworking: true  
    iam:
      withAddonPolicies:
        albIngress: true      # Required for ALB Ingress Controller
    tags:
      Environment: production
    
# VPC Configuration    
vpc:
  cidr: "10.0.0.0/16"
  nat:
    gateway: Single          # Single NAT Gateway to reduce costs

# Control Plane Logging - Minimal for cost saving
cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "api"]  # Only essential logs